/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WeatherDataAggregate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5924006257461214388L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WeatherDataAggregate\",\"fields\":[{\"name\":\"location\",\"type\":\"string\"},{\"name\":\"average_temperature\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WeatherDataAggregate> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WeatherDataAggregate> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WeatherDataAggregate> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WeatherDataAggregate> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WeatherDataAggregate> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WeatherDataAggregate to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WeatherDataAggregate from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WeatherDataAggregate instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WeatherDataAggregate fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence location;
  private double average_temperature;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WeatherDataAggregate() {}

  /**
   * All-args constructor.
   * @param location The new value for location
   * @param average_temperature The new value for average_temperature
   */
  public WeatherDataAggregate(java.lang.CharSequence location, java.lang.Double average_temperature) {
    this.location = location;
    this.average_temperature = average_temperature;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return location;
    case 1: return average_temperature;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: location = (java.lang.CharSequence)value$; break;
    case 1: average_temperature = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public java.lang.CharSequence getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(java.lang.CharSequence value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'average_temperature' field.
   * @return The value of the 'average_temperature' field.
   */
  public double getAverageTemperature() {
    return average_temperature;
  }


  /**
   * Sets the value of the 'average_temperature' field.
   * @param value the value to set.
   */
  public void setAverageTemperature(double value) {
    this.average_temperature = value;
  }

  /**
   * Creates a new WeatherDataAggregate RecordBuilder.
   * @return A new WeatherDataAggregate RecordBuilder
   */
  public static WeatherDataAggregate.Builder newBuilder() {
    return new WeatherDataAggregate.Builder();
  }

  /**
   * Creates a new WeatherDataAggregate RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WeatherDataAggregate RecordBuilder
   */
  public static WeatherDataAggregate.Builder newBuilder(WeatherDataAggregate.Builder other) {
    if (other == null) {
      return new WeatherDataAggregate.Builder();
    } else {
      return new WeatherDataAggregate.Builder(other);
    }
  }

  /**
   * Creates a new WeatherDataAggregate RecordBuilder by copying an existing WeatherDataAggregate instance.
   * @param other The existing instance to copy.
   * @return A new WeatherDataAggregate RecordBuilder
   */
  public static WeatherDataAggregate.Builder newBuilder(WeatherDataAggregate other) {
    if (other == null) {
      return new WeatherDataAggregate.Builder();
    } else {
      return new WeatherDataAggregate.Builder(other);
    }
  }

  /**
   * RecordBuilder for WeatherDataAggregate instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WeatherDataAggregate>
    implements org.apache.avro.data.RecordBuilder<WeatherDataAggregate> {

    private java.lang.CharSequence location;
    private double average_temperature;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(WeatherDataAggregate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.location)) {
        this.location = data().deepCopy(fields()[0].schema(), other.location);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.average_temperature)) {
        this.average_temperature = data().deepCopy(fields()[1].schema(), other.average_temperature);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing WeatherDataAggregate instance
     * @param other The existing instance to copy.
     */
    private Builder(WeatherDataAggregate other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.location)) {
        this.location = data().deepCopy(fields()[0].schema(), other.location);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.average_temperature)) {
        this.average_temperature = data().deepCopy(fields()[1].schema(), other.average_temperature);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public WeatherDataAggregate.Builder setLocation(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.location = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public WeatherDataAggregate.Builder clearLocation() {
      location = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'average_temperature' field.
      * @return The value.
      */
    public double getAverageTemperature() {
      return average_temperature;
    }


    /**
      * Sets the value of the 'average_temperature' field.
      * @param value The value of 'average_temperature'.
      * @return This builder.
      */
    public WeatherDataAggregate.Builder setAverageTemperature(double value) {
      validate(fields()[1], value);
      this.average_temperature = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'average_temperature' field has been set.
      * @return True if the 'average_temperature' field has been set, false otherwise.
      */
    public boolean hasAverageTemperature() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'average_temperature' field.
      * @return This builder.
      */
    public WeatherDataAggregate.Builder clearAverageTemperature() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WeatherDataAggregate build() {
      try {
        WeatherDataAggregate record = new WeatherDataAggregate();
        record.location = fieldSetFlags()[0] ? this.location : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.average_temperature = fieldSetFlags()[1] ? this.average_temperature : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WeatherDataAggregate>
    WRITER$ = (org.apache.avro.io.DatumWriter<WeatherDataAggregate>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WeatherDataAggregate>
    READER$ = (org.apache.avro.io.DatumReader<WeatherDataAggregate>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.location);

    out.writeDouble(this.average_temperature);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.location = in.readString(this.location instanceof Utf8 ? (Utf8)this.location : null);

      this.average_temperature = in.readDouble();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.location = in.readString(this.location instanceof Utf8 ? (Utf8)this.location : null);
          break;

        case 1:
          this.average_temperature = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










