apiVersion: v1
kind: Service
metadata:
  name: weather-forecast-app-service
spec:
  selector:
    app: weather-forecast-app
  ports:
  - protocol: TCP
    port: 80  # The port on which the service is exposed
    targetPort: 8080  # The port on the container that the service should route to
  type: LoadBalancer  # Use LoadBalancer for external access or ClusterIP for internal access
